name: Run Python Script

on:
  schedule:
    - cron: "*/30 * * * *" # A cada 30 minutos
  workflow_dispatch: # Permite rodar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create JSON file from secret
        run: |
          echo "${{ secrets.MY_JSON_KEY }}" | base64 --decode > passaporto-442722-14b8199d85ae.json

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run script
        run: python login.py
