name: Run Python Script

on:
  schedule:
    - cron: "*/30 * * * *" # A cada 30 minutos
  workflow_dispatch: # Permite rodar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python login.py
